// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDObo55W_Jztb6rdvGjFZe5DEyTtjP9K4k',
    appId: '1:127948861654:android:d5815276497a7135419977',
    messagingSenderId: '127948861654',
    projectId: 'tmstar-845d4',
    storageBucket: 'tmstar-845d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHq3awV2KLV6N3XBpg9gHWUY6PU9cl1wo',
    appId: '1:127948861654:ios:90895e6560ab9944419977',
    messagingSenderId: '127948861654',
    projectId: 'tmstar-845d4',
    storageBucket: 'tmstar-845d4.appspot.com',
    androidClientId: '127948861654-4jb7v39melmver81ip6pkllv939rnch5.apps.googleusercontent.com',
    iosClientId: '127948861654-ngu6k58psc9e08tp3jq47h1e0db9hvtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tmstarFirebase',
  );
}
